### ISSUE TITLE
如何使用v2ray的配置文件？

### ISSUE THREAD

**Issue by xxyyffyeah** [lbp0200/v2ray-vultr#2]
在重新创建一个服务器后，我下载了最新的v2ray，我应该在哪里更改配置文件，在启动了以后，是一个命令行界面，我应该输入什么？谢谢！

**Comment by lbp0200** [comment]
`我下载了最新的v2ray，我应该在哪里更改配置文件，在启动了以后，是一个命令行界面，我应该输入什么？谢谢！`
这是在配置客户端吗？
`v2ray路径 -config 配置文件的路径`

**Comment by xxyyffyeah** [comment]
是用client.json覆盖config.json吗？
在这以后应该怎么做呢？

**Comment by lbp0200** [comment]
不熟悉v2ray，建议更换ssr，https://github.com/lbp0200/ssr-vultr
